{% set name = "dgllife" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dgllife-{{ version }}.tar.gz
  sha256: 1ee6b1a10e4a564a4d0e339b776f038e7b0c7d0d1ef7fd9d6f9e93e9a36ff5c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hyperopt
    - joblib
    - networkx >=2.1
    - numpy >=1.14.0
    - pandas
    - python >=3.6
    - requests >=2.22.0
    - scikit-learn >=0.22.2
    - scipy >=1.1.0
    - tqdm

# disable pip check because of https://github.com/awslabs/dgl-lifesci/pull/179
test:
  commands:
    # - pip check
    # NOTE(hadim): we can't import `dgllife` since it requires  the `dgl` package.
    # but we can at least check it exists in the path.
    - python -c "import importlib.util; assert importlib.util.find_spec('dgllife') is not None"
  requires:
    - pip

about:
  home: https://github.com/awslabs/dgl-lifesci
  summary: DGL-based package for Life Science
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
